### ISSUE TITLE
Fullscreen Mode Bugs

### ISSUE THREAD

**Issue by andwhyisit** [isage/nxengine-evo#12]
In the windows build of v2.3 certain graphics such as UI, the player, the message box, and cursors tend to disappear with a switch from fullscreen to windowed or from windowed to fullscreen. This can also break the title screen background, however that varies by resolution. Switching the resolution seems to fix the visuals, but selecting a resolution larger than what your graphics card supports (1600x1200 and 1920x1080 for me) while you are in fullscreen mode can lead to some very strange behaviour.

Tested on Windows 7 64-bit.

**Comment by isage** [comment]
Should be fixed in latest release
