### ISSUE TITLE
NXengine appears and disappears when attempting to running

### ISSUE THREAD

**Issue by thegreatestminer** [isage/nxengine-evo#14]
So basically after copying the files and DLLs and running extract_Win32.exe, I tried running nx_Win32.exe, and it appeared for a second then disappeared.

Below is a video of exactly what I did.

https://streamable.com/kosq5

P.S. The releases on GitHub work fine.

**Comment by isage** [comment]
There should be debug.txt log in /Users/[your-user]/AppData/Roaming/nxengine/nxengine-evo
or in /Users/[your-user]/Application Data/nxengine/nxengine-evo

**Comment by thegreatestminer** [comment]
There was a debug.l file instead:
```
Loading settings...
Couldn't open file C:\Users\ULTIMA7\AppData\Roaming\nxengine\nxengine-evo\settings.dat.
No saved settings; using defaults.
Graphics::SetResolution(2)
DW: 1600, DH: 900
Disabling 1280x1024
Disabling 1600x1200
Disabling 1920x1080
Setting scaling 2
DW: 1600, DH: 900
Disabling 1280x1024
Disabling 1600x1200
Disabling 1920x1080
SDL_CreateWindow: 640x480 @ 16bpp
Graphics::InitVideo: using: direct3d renderer
Graphics::FlushAll()
 error << SIFLoader::LoadHeader: failed to open file 'data/sprites.sif' >>
 error << Failed to initialize graphics. >>
```

**Comment by isage** [comment]
Have you copied data folder from repo to destination?

**Comment by thegreatestminer** [comment]
Oh, I didn't. Was I supposed to copy both data folders, the 1st from the repo, the 2nd from cavestoryen.zip?

Currently I cannot test because I'm on mobile

**Comment by isage** [comment]
Yep, both.

**Comment by thegreatestminer** [comment]
Ah, will try a little later, still only have access to my phone.

**Comment by thegreatestminer** [comment]
OK, finally was able to test it.

It works! Thanks alot!
