### ISSUE TITLE
Directional buttons go insane when playing with a joypad

### ISSUE THREAD

**Issue by Amitari** [isage/nxengine-evo#18]
I've tried playing Cavestory using nxengine-evo with a joypad. Unfortunately, when you press a directional button, it keeps staying pressed until you press another one. This happens with both the vertical and horizontal ones, the vertical ones are most noticeable in the menu, of course. I have tried with 2 USB joypads, both of them results in this unplayable state, and they both work just like they should on any other game.

**Comment by isage** [comment]
Are those buttons digital or analog? What pads and what OS are you using?
I haven't experienced those issues with logitech F310, logitech rumblepad and xbox 360 pads.

**Comment by Amitari** [comment]
They're digital, it's a d-pad, and I'm running GNU/Linux. The first pad I was using is a Super Famicom controller connected using an unbranded adapter. It does however show up as "Lakeview Research WiseGroup Ltd, MP-8866 Dual Joypad" when running lsusb. The other controller is a iBuffalo BSGP1601BK.

**Comment by isage** [comment]
Can you run `jstest --event /dev/input/js0`
press dpad buttons and provide output?

**Comment by Amitari** [comment]
Here's the output of my terminal when I'm pressing the dpad of the SuFami joypad in clockwise directions, plus the L and R buttons just to make sure.

> [user@halebop ~]$ jstest --event /dev/input/js0
> Joystick (SFC/USB Pad) has 2 axes and 8 buttons. Driver version is 2.1.0.
> Testing ... (interrupt to exit)
> Event: type 129, time 1431605172, number 0, value 0
> Event: type 129, time 1431605172, number 1, value 0
> Event: type 129, time 1431605172, number 2, value 0
> Event: type 129, time 1431605172, number 3, value 0
> Event: type 129, time 1431605172, number 4, value 0
> Event: type 129, time 1431605172, number 5, value 0
> Event: type 129, time 1431605172, number 6, value 0
> Event: type 129, time 1431605172, number 7, value 0
> Event: type 130, time 1431605172, number 0, value 0
> Event: type 130, time 1431605172, number 1, value 0
> Event: type 2, time 1431607655, number 1, value -32767
> Event: type 2, time 1431607832, number 1, value 0
> Event: type 2, time 1431608785, number 0, value 32767
> Event: type 2, time 1431608945, number 0, value 0
> Event: type 2, time 1431611545, number 1, value 32767
> Event: type 2, time 1431611642, number 1, value 0
> Event: type 2, time 1431612122, number 0, value -32767
> Event: type 2, time 1431612208, number 0, value 0
> Event: type 2, time 1431613002, number 1, value -32767
> Event: type 2, time 1431613048, number 1, value 0
> Event: type 2, time 1431614135, number 0, value 32767
> Event: type 2, time 1431614232, number 0, value 0
> Event: type 2, time 1431615128, number 0, value 32767
> Event: type 2, time 1431615175, number 0, value 0
> Event: type 2, time 1431616122, number 0, value 32767
> Event: type 2, time 1431616202, number 0, value 0
> Event: type 2, time 1431616975, number 1, value -32767
> Event: type 2, time 1431617048, number 1, value 0
> Event: type 2, time 1431617785, number 1, value 32767
> Event: type 2, time 1431617872, number 1, value 0
> Event: type 2, time 1431618225, number 0, value -32767
> Event: type 2, time 1431618338, number 0, value 0
> Event: type 2, time 1431618642, number 1, value -32767
> Event: type 2, time 1431618712, number 1, value 0
> Event: type 2, time 1431619025, number 0, value 32767
> Event: type 2, time 1431619122, number 0, value 0
> Event: type 2, time 1431619425, number 1, value 32767
> Event: type 2, time 1431619512, number 1, value 0
> Event: type 2, time 1431619848, number 0, value -32767
> Event: type 2, time 1431619938, number 0, value 0
> Event: type 2, time 1431620392, number 1, value -32767
> Event: type 2, time 1431620432, number 1, value 0
> Event: type 1, time 1431620968, number 4, value 1
> Event: type 1, time 1431621042, number 4, value 0
> Event: type 1, time 1431621465, number 4, value 1
> Event: type 1, time 1431621528, number 4, value 0
> Event: type 1, time 1431622362, number 5, value 1
> Event: type 1, time 1431622458, number 5, value 0
> Event: type 2, time 1431622785, number 1, value -32767
> Event: type 2, time 1431622888, number 1, value 0
> Event: type 2, time 1431623105, number 0, value 32767
> Event: type 2, time 1431623192, number 0, value 0
> Event: type 2, time 1431623522, number 1, value 32767
> Event: type 2, time 1431623618, number 1, value 0
> Event: type 2, time 1431623898, number 0, value -32767
> Event: type 2, time 1431624002, number 0, value 0
> Event: type 2, time 1431624305, number 1, value -32767
> Event: type 2, time 1431624385, number 1, value 0
> Event: type 2, time 1431624665, number 0, value 32767
> Event: type 2, time 1431624738, number 0, value 0
> Event: type 2, time 1431625042, number 1, value 32767
> Event: type 2, time 1431625138, number 1, value 0
> Event: type 2, time 1431625448, number 0, value -32767
> Event: type 2, time 1431625528, number 0, value 0
> ^C
> [user@halebop ~]$

**Comment by isage** [comment]
Well, i'm really puzzled. Did you compile nxengine yourself?
Can you please provide your distro and it's version, version of libsdl and gcc.

**Comment by Amitari** [comment]
I'm pretty sure I have built it myself since there doesn't seem to be any finished builds available. I was gonna try recompiling it now, but it  doesn't wanna work, the make-command only spits out "make: *** No targets specified and no makefile found.  Stop." when I'm following the instructions.

I'm running Manjaro Linux, which is a rolling release. I have sdl-1.2.15-9, sdl2-2.0.5-4, and gcc-7.2.0-3 right now. Not sure if I had these version when I compiled the software.

**Comment by isage** [comment]
I've installed manjaro, but, sadly, couldn't reproduce this issue. All is working fine for me.

**Comment by Amitari** [comment]
I just realized that there was a pre-made build hosted on GitHub, and it must have been that one I used. I tried out the latest version, but it gave the same odd result. Luckily, since it doesn't need analog control, I can get around this by mapping the controls to the keyboard and using software that converts the controller presses to keystrokes.

**Comment by isage** [comment]
Well, you can try building it yourself. Although prepackaged version comes with required libs, there can be some clashing with system ones.
As for your build problem, make sure `cmake -DCMAKE_BUILD_TYPE=Release ..` completes without errors

**Comment by isage** [comment]
Hm , it looks like occasionally, when using sticks on gamepad one of the directions can became stuck for some time.
Reopening.
