### ISSUE TITLE
Cutscene retrigger during first Balrog fight

### ISSUE THREAD

**Issue by FayneAldan** [isage/nxengine-evo#19]
I found a cutscene retrigger bug. During the fight with Balrog (or simply in the room if you say you don't want to fight), if you press down where Sue was before taken away by Misery, you'll talk to her again and retrigger the cutscene.
![](https://i.imgur.com/KNfUQHm.png)
![](https://i.imgur.com/ibWR0xv.png)
![](https://i.imgur.com/XRPycTn.png)
![](https://i.imgur.com/kDhpn0o.png)
![](https://i.imgur.com/OoqyOQU.png)
I originally posted this issue somewhat upstream (libretro/nxengine-libretro#41), but I have confirmed this issue exists in evo 2.5 as well.

**Comment by isage** [comment]
It looks like after Sue is snatched by Misery, trigger point is not destroyed. I'll look into it.
