### ISSUE TITLE
widescreen question

### ISSUE THREAD

**Issue by fr500** [isage/nxengine-evo#3]
hi
I'm backporting some of your patches to the nxengine-libretro port, I'll try to cherrypick the commits untouched so you preseve authorship were possible.

Just a question, are these commits all I need for fully functional widescreen?

https://github.com/isage/nxengine-evo/commit/bdf4e822e38ccd665c60a76d4b08f1bd3b86b3ea
https://github.com/isage/nxengine-evo/commit/23cead80dbc789e226f314000374d908174573b9

I have most of the patches integrated but I was wondering if I was missing some other commits that might fix some of the glitches.

https://github.com/libretro/nxengine-libretro

**Comment by isage** [comment]
Basically, yes. And this for variable: 0547310bd01e5a09ac9948d7da511cbd8ce8164a
But I'm pretty sure, you'll also need this, to fix drawing artifacts, introduced by widescreen:
ef6b51829bc945894a6208a72f0ff7ad28a9f1e4
337f98dfb2c9d2628b85d0b78f49955a9b7c9f43
d15889513e2407f4005541d54e5e2e7d9e366d36
eae2ab7da44c864e355e6910dc55e6e995c21d4a
287e66de285fc9dd67eb60bba25b527b2f0462a0
8c3c9bf51d6aa955ae180946f7cdd600ec5aa54b
b861fd309ab3c44a79dc4eb8e0ae1a5d06509929
ed6321d4a7dded94237581047da06a3522b63a8e
5ae99fb07af90372dcc80ec0aa109b7ef501c724
745b46a66467e9f2a21b84ac2aa2bbcb82656fab

**Comment by isage** [comment]
I'm not sure if that's all, or if you really need all of these, sorry.

**Comment by fr500** [comment]
np, that's a lot of help already, thanks
