### ISSUE TITLE
Send code to upstream?

### ISSUE THREAD

**Issue by hugomg** [isage/nxengine-evo#5]
I noticed that there are a lot of different repositories like this one that have updates to the NXEngine. Has anyone ever putting all those changes back together and  contributing them back to the upstream? The current state of things is very fragmented...

I ask this because I just noticed that some of the bugs I found on NXEngine are already fixed here.

**Comment by isage** [comment]
I don't think so. I'm not even sure upstream is alive. Problem is, there's
ios port, which uses some ios-only features, libretro port, and my sdl2
port. And they are not quite compatible. Afaik, however, ios and libretro
ports cherrypicked some of my enhancements and fixes.

**Comment by hugomg** [comment]
Earlier this week I sent a patch to email listed on the [sourceforge website](http://nxengine.sourceforge.net/) and got a prompt response so I guess they are alive, although inactive :).

But thanks for your answer, it confirms my suspicion that the bigger problem was that the different ports diverged because they target different platforms.
